In [2]:
#import pandas
import pandas as pd
#import numpy
import numpy as np
#import matplotlib
import matplotlib.pyplot as plt
#import seaborn
import seaborn as sns

In [3]:
# use pandas to import csv file
df = pd.read_csv("House_Rent_main7.csv")

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Assuming you have your data in a pandas DataFrame called 'df'
X = df.drop('BHK', axis=1)
y = df['BHK']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the KNN classifier
k = 3  # choose the value of k
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn.predict(X_test)

# Evaluate the performance of the classifier
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[191  41   0   0]
 [121 321  23   0]
 [  6  88 107   5]
 [  0   5  32   4]]
              precision    recall  f1-score   support

           1       0.60      0.82      0.69       232
           2       0.71      0.69      0.70       465
           3       0.66      0.52      0.58       206
           4       0.44      0.10      0.16        41

    accuracy                           0.66       944
   macro avg       0.60      0.53      0.53       944
weighted avg       0.66      0.66      0.65       944

